
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    ID = 2F,
    Brand = @"Jaguar",
    Model = @"Generic Model 2",
    Year = 2003F,
    Color = @"Silver",
    Price = 58620F,
    Condition = @"New",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Mileage with predicted Mileage from sample data...\n\n");


Console.WriteLine($"ID: {2F}");
Console.WriteLine($"Brand: {@"Jaguar"}");
Console.WriteLine($"Model: {@"Generic Model 2"}");
Console.WriteLine($"Year: {2003F}");
Console.WriteLine($"Color: {@"Silver"}");
Console.WriteLine($"Mileage: {89937F}");
Console.WriteLine($"Price: {58620F}");
Console.WriteLine($"Condition: {@"New"}");


var predictionResult = MLModel1.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Mileage: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

